import React, { Component } from 'react';

//components
import hockey from './files/hockey.jpg';
//includes


  class About extends Component {
    render() {
      return (
        <div className ="container-fluid">
            <div className="top">
              <img src={hockey} alt="hockey"/>
              <h1><mark>About Me</mark></h1>
            </div>
            <div className ="content">  
              <p className="opening">My name is Andrew Bauer, and I am a fourth-year computer science major at Georgia Tech with concentrations in in Intelligence and People. I have academic and career interests in product management, human computer interaction, and data science. This summer, I am working at American Express as an Associate Product Intern, where I am working as a product manager for their Digital Banking Product Portfolio team. </p>         
              <p>Prior to my enrollment at Georgia Tech, a majority of my ventures revolved around soft skill development. For four years I served as the volunteer director of the Teams For Kids Foundation, Inc., a 501(c) non-profit organization founded in 2014 that seeks to provide children from underserved families in New Jersey with the ability to participate in sports. I maximized fundraising through writing grants, planning events, direct mail solicitations, and launching the organization’s largest initiative: The Student Athlete Ambassador Program, where I recruited and worked with high schoolers from 15 different high schools in the state of New Jersey, who raised funds and awareness to support the organization’s mission. The program was awarded a New Jersey State Governor’s Jefferson Award in the Youth Volunteer Group category in 2019, while I personally was a medalist for the 2018 New Jersey State Governor’s Jefferson Award in the Service to Youth category. Through these experiences, I learned valuable skills of leadership, verbal and written communication, and collaboration, and was exposed to social inequities, something growing within the field of technology.</p>      
              <p>At Georgia Tech, my well-developed soft skills have become complimented with technical skills. During the Fall 2020 semester, I worked as a Data Scientist for the Discussion Forum sub team of the Data Driven Education Vertically Integrated Project at Georgia Tech. On this team, I collected and analyzed data from the academic discussion boards of Georgia Tech’s learning management systems using languages and packages such as python, pandas, and numPy. Additionally, I supported the front-end team using python libraries such as matplotlib to visualize this data.  Ultimately, my team and I used natural language processing and sentiment analysis techniques to create python scripts and visualizations to be used in a web application with the goal of aiding Georgia Tech professors in their instruction. This was my first experience working on a software team and with big data, and it motivated me to continue to explore these fields in my coursework and in projects.</p>
              <p>Over time, I gained further experience in software and application development. I have completed coursework in object-oriented programming, data structures and algorithms, objects and design, and in artificial intelligence and in machine learning. During the Spring and Fall 2021 semesters, I completed my Junior Design Project: a biodiversity surveying game called ATL Wildin’. I worked primarily as the front-end developer of this team, utilizing HTML, Javascript, CSS, bootstrap, and python to develop the user interface of the web application, which was a game where users would be presented photos of animals taken on Georgia Tech’s campus greenspaces, and wuld be prompted to tag the images to identify the animal presented as a means of data collection. The application was a Django web application, using mySQL databases and a file share server to store information on the image and animal data. Our team consisted of 6 members, and we utilized agile methodologies, communicated with a client, and performed user research and created UML diagrams to document and develop our application.</p>
              <p>I boast extensive knowledge and skills in the field of product management. During Summer 2021, I worked as an Enterprise Transformation intern at Grant Thornton. There, I completed product management work on the firm’s developing client data platform. I was responsible for managing the user face component of the product, where users would be able to search for datasets to send to downstream applications. I worked with UX designers and the outsourced software team to ensure the implementation of business requirements. In addition to this, I completed IT analytics work by analyzing the data on the company’s AI chatbot’s unresolved requests, creating a power BI visualization to present my results on where the chatbot’s knowledge base needs to be revised and added to in an effort to improve its performance. Overall, I found that creating products with the end-user and business needs in mind is extremely appealing to me, and something I desire to continue to do after college.</p>
              <p>I have completed numerous projects on machine learning, user interface design, and data visualization from my coursework at Georgia Tech. Through these projects I gained proficiency in creating frameworks using figma, machine learning techniques from python packages such as sklearn and pytorch, and data visualization tools such as d3.js, tableau, and power BI. For more information on some of my projects, please look at the “Projects” section of this webpage, which was developed using React.js.</p>
              <p>Outside of academics and work, I am a member of my fraternity, Alpha Epsilon Pi at Georgia Tech, where I served as social chair during the 2020-2021 school year, as vice president during the 2021 calendar year, and as philanthropy chair during the 2021-2022 school year. Additionally, I play on the Georgia Tech Club Ice Hockey Team and used to play the trombone in a jazz combo at Georgia Tech. In my free time I enjoy watching sports, studying basketball statistics and analytics, listening to music, reading books, and trying new foods.</p>
            </div>
        </div>
        
      );
  }  
}


export default About;